# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: lunchat
  password: lunch
  host: localhost

development:
  <<: *default
  database: lunchat_dev

test:
  <<: *default
  database: lunchat_test

